### ISSUE TITLE
Remaining lects and pracs

### ISSUE THREAD

**Issue by erex** [distanceworkshops/standrews-2019#3]
Will upload remaining intro workshop lecture PDFs on Friday (need the use of office computer to do a legitimate PowerPoint to PDF conversion).  I've decided upon full page (A4) landscape for PDF format; folks can write sticky notes onto the slides.

That brings up a todo: participants should be asked to have Acrobat installed on their machines before arrival.

**Comment by erex** [comment]
### Introductory workshop materials

- all 10 lectures uploaded as PDFs
- all 9 practicals uploaded
  - if you're curious, there's no prac for field methods lecture block
  - both pdf (with instructions and solutions)
  - along with rmd files

**Comment by erex** [comment]
I'll note here that although Louise revised 17 lectures, I've condensed those 13 down to 8 thus:
A=1.2+1.3
B=1.4+1.5
C=2.1+2.3
D=2.4+5.1
E=3.1+3.2
F=Laura constructed
G=5.2
H=5.4+5.5
I=6.2
J=4.6+4.3+2.5

the few edits I made to A-J after ~30Jul19 are not reflected in the original 17 lectures

**Comment by erex** [comment]
Whoops.  I realise looking at the list above that Lecture 4.3 on sample size calculations has not been folded into the current block-scheme of lectures.  I'll need to tuck that lecture into Lecture J (at the end).

**Comment by dill** [comment]
I'm moving these across now, hopefully this won't cause too many issues...

**Comment by dill** [comment]
practicals have been moved in git, might take a while for the site to update...

**Comment by dill** [comment]
slide listing should now also be in place.

I am assuming I should delete `BlockJ-field.pdf` in favour of `BlockJ-field-sampsize.pdf`?

**Comment by erex** [comment]
Correct for the moment, but the format of BlockJ-field-sampsize.pdf is inconsistent with other PDFs.  I'll need to sort that Saturday as well.

**Comment by erex** [comment]
uploaded BlockJ lecture as PDF properly formatted.

**Comment by dill** [comment]
Great. Is that all materials done now? (Along with #4)

**Comment by erex** [comment]
8 lecture PDFs, 9 exercise Rmds, 9 exercise PDFs.  All present and accounted for; done to the best of my abilities.

**Comment by dill** [comment]
Ace. Thanks. Will close this issue then.
